replicaCount: 2

image:
  repository: jshwj/nextjs-test
  pullPolicy: IfNotPresent
  tag: "v1.0"

imagePullSecrets: []

service:
  enabled: true
  type: NodePort
  port: 3000
  nodePort: 30007

serviceAccount:
  create: true
  name: ""

autoscaling:
  enabled: false

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: test.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

livenessProbe:
  httpGet:
    path: /about
    port: 3000

readinessProbe:
  httpGet:
    path: /contact
    port: 3000

resources: {}

securityContext: {}
podSecurityContext: {}

podAnnotations: {}
podLabels: {}
