apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-helm-projects
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
        revision: main
        directories:
          - path: "helm-projects/*"
  template:
    metadata:
      name: "{{path.basename}}-helm"
    spec:
      project: default
      sources:
        - repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
          targetRevision: main
          path: helm-base
          helm:
            valueFiles:
              - $refs/{{path}}/values.yaml
        - repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
          targetRevision: main
          ref: refs
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true # git에서 제거된 리소스를 쿠버네티스에서도 삭제
          selfHeal: true # 클러스터 상태가 git 상태랑 다르면 복구
        syncOptions:
          - CreateNamespace=true # 해당 ns가 존재하지 않을 경우, 이 옵션이 없으면 자동으로 ns 안 만든다.
