apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-helm-projects
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
        revision: main
        directories:
          - path: "helm-projects/*"
  template:
    metadata:
      name: "{{path.basename}}-helm"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
          targetRevision: main
          ref: valuesref
        - repoURL: "https://github.com/JSHWJ/Test-Helm-Chart.git"
          targetRevision: main
          path: helm-base
          helm:
            valueFiles:
              - $valuesref/helm-projects/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
